### ISSUE TITLE
Check internet connectivity thru VPN connection

### ISSUE THREAD

**Issue by azinchen** [azinchen/nordvpn#3]

**Comment by saikpr** [comment]
simply `docker exec -it vpn curl portquiz.net` works?

**Comment by azinchen** [comment]
Implemented additional environment variables

 * `CHECK_CONNECTION_CRON` - Set period of checking Internet connection in format for crontab file. Disabled by default.
 * `CHECK_CONNECTION_URL` - Use list of URI for checking Internet connection.
 * `CHECK_CONNECTION_ATTEMPTS` - Set number of attemps of checking. Default value is 5.
 * `CHECK_CONNECTION_ATTEMPT_INTERVAL` - Set sleep timeouts between failed attepms. Default value is 10.
