### ISSUE TITLE
docker intall error "missing signature key"

### ISSUE THREAD

**Issue by jkj1234** [azinchen/nordvpn#377]
docker install error

[root@vmi---- ~]# docker pull azinchen/nordvpn
Using default tag: latest
Trying to pull repository docker.io/azinchen/nordvpn ...
missing signature key

Is there a solution to the error?

**Comment by azinchen** [comment]
I don't see this error, probably it is temporal Docker Hub error.
Try using the GitHub repository as an alternate source, `azinchen/nordvpn` is released to both repositories at the same time.

```
docker pull ghcr.io/azinchen/nordvpn
```
