### ISSUE TITLE
Unrecognized option or missing or extra parameter

### ISSUE THREAD

**Issue by Joly0** [azinchen/nordvpn#417]
Hey, i tried adding the following variable:
-e 'TECHNOLOGY'='pptp'
and after starting up, i get this error constantly:
Options error: Unrecognized option or missing or extra parameter(s) in /tmp/nordvpn.ovpn:3: proto (2.6.8)
Use --help for more information.

**Comment by Joly0** [comment]
Ok, from looking at thise function https://github.com/azinchen/nordvpn/blob/8eb11217d3d23b861be28b836e3a81216a836def/root/usr/bin/createvpnconfig.sh#L147 there seems to be 2 issues here.
First thise line https://github.com/azinchen/nordvpn/blob/8eb11217d3d23b861be28b836e3a81216a836def/root/usr/bin/createvpnconfig.sh#L132C11-L132C11
should be `ident=$(echo "$nvtechnologies" | jq -r --arg NAME "$input" 'select(.identifier == $NAME) | .identifier')`
and second the function only returns something, if the ident variable has udp or tcp in it, which is not the case for technologies like pptp

**Comment by azinchen** [comment]
@Joly0 , the `azinchen/nordvpn` image supports OpenVPN protocol and technologies only.

**Comment by Joly0** [comment]
Ok? Then maybe adjust your technology list here https://github.com/azinchen/nordvpn/blob/master/TECHNOLOGIES.md
It indicates, that all these technologies are working and supported

**Comment by azinchen** [comment]
It is mentioned in the [list](https://github.com/azinchen/nordvpn?tab=readme-ov-file#environment-variables) of environment variables.

**Comment by Joly0** [comment]
Hm, ok. Wasnt that obvious to me. But thanks
