### ISSUE TITLE
Repeating error line in logs makes gigantic logs

### ISSUE THREAD

**Issue by epicylon** [azinchen/nordvpn#8]
Hey, 

I'm getting this repeating line
`Tue Aug 27 03:06:29 2019 AEAD Decrypt error: bad packet ID (may be a replay): [ #676043 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings`
in my logs, and it makes the logs up to 50MB and crashes the container if I don't clean them regularly.

**Comment by azinchen** [comment]
I'll add OPENVPN_OPTS environment variable with "--mute-replay-warnings" value by default.

**Comment by niXta1** [comment]
I think it's better to actually fix the issue by lowering the MTU by:
"--mssfix 1500"
And lower the 1500 until the error goes away.

**Comment by epicylon** [comment]
It's an extra argument and not an environmental variable right? 

Seems to fix the issue if used like `--mute-replay-warnings` **not** `-e OPENVPN_OPTS=--mute-replay-warnings`

**Comment by azinchen** [comment]
This environment variable is not implemented yet.

This variable will be used to pass additional commands to openvpn - --mute-replay-warnings, --mssfix, what-ever-else.

**Comment by epicylon** [comment]
Gotcha, thanks for the quick replies!

**Comment by azinchen** [comment]
The `OPENVPN_OPTS` environment variable has been implemented in azinchen/nordvpn:beta. The variable is empty by default. Could you check that the `OPENVPN_OPTS` initialized with `--mute-replay-warnings` or `--mssfix 1452` fix this issue.
