### ISSUE TITLE
1.1.0 Issue with api.nordvpn.com

### ISSUE THREAD

**Issue by sachinwadhwa** [azinchen/nordvpn#86]
Not connecting to VPN, possibly due to:

iptables v1.8.7 (legacy): host/network `api.nordvpn.com' not found
Try `iptables -h' or 'iptables --help' for more information.
[cont-init.d] 40-whitelistnetwork: exited 0.
[cont-init.d] 50-createvpnconfig: executing...
Select NordVPN server and create config file
Apply filter technology "OpenVPN UDP"
Request list of recommended servers
Request servers in "Canada", 0 servers received
Request servers in "United States", 0 servers received
Request servers in "United Kingdom", 0 servers received
0 recommended servers in pool
ERROR: list of selected servers is empty

**Comment by azinchen** [comment]
Hi @sachinwadhwa,

Are you from country with VPN restriction? Check that NordVPN is not blocked on your host.

```
ping api.nordvpn.com
curl -s "https://api.nordvpn.com/v1/servers/recommendations" | jq '.[] | .name'
```

**Comment by sachinwadhwa** [comment]
Works perfectly fine with 1.0.1:

Select NordVPN server and create config file
Apply filter technology "OpenVPN UDP"
20 recommended servers in "Canada"
20 recommended servers in "United States"
20 recommended servers in "United Kingdom"
60 recommended servers in pool
--- Top 20 servers in filtered pool ---
us8651.nordvpn.com: 3
us8646.nordvpn.com: 4
us5955.nordvpn.com: 4
us5844.nordvpn.com: 5
us8509.nordvpn.com: 4
us8439.nordvpn.com: 4

**Comment by azinchen** [comment]
Please check this version

```docker pull azinchen/nordvpn:fixdnsresolver```

**Comment by sachinwadhwa** [comment]
still same issue on nordvpn:fixdnsresolver

**Comment by azinchen** [comment]
Pull and try again

**Comment by sachinwadhwa** [comment]
worked this time.

**Comment by azinchen** [comment]
That's great and it is sad :(. I tried to block all outgoing traffic, even to DNS resolver, except to VPN server, local network and whitelist hosts. 1.1.0 works fine on my setup, this is why I released it.

**Comment by sachinwadhwa** [comment]
I understand the reason, but I guess you should block is after successful connection or caching the server list... but you need to unblock it after disconnection.

**Comment by azinchen** [comment]
Merged to `master` 248280caa839b9cdf7508805bc5305923db41f62, v1.2.0 has been released.

**Comment by azinchen** [comment]
Leave it open for additional conversation and possible new solution.

**Comment by oscar-corredor** [comment]
Im running on this problem with latest version, is there anything I'm missing?
