### ISSUE TITLE
Remotely connect to containers that are running through the VPN container?

### ISSUE THREAD

**Issue by GOvEy1nw** [azinchen/nordvpn#9]
Is this possible?

I have a Synology NAS where some of my docker containers run through the VPN container.

This works great locally, but at the minute it does mean I can't access any of those containers remotely.

Is there something I can do to keep it running through the VPN container but also be able to access it remotely?

**Comment by niXta1** [comment]
"Remotely" do you mean in your LAN or outside your LAN through your NATed router?

**Comment by GourouLubrik** [comment]
And by accessing, you mean routing network traffic or login into it through ssh ?

**Comment by azinchen** [comment]
> Is there something I can do to keep it running through the VPN container but also be able to access it remotely?

I suppose, `CATEGORY=Dedicated IP` should work Ok in this case. You must subscribe to Dedicated IP from NordVPN in addition.

I case if you need only control your container outside of home network, just forward necessary ports, for example, 9091 for Transmission RPC.

**Comment by BobWs** [comment]
> And by accessing, you mean routing network traffic or login into it through ssh ?
> 
> Althrough I don't use nordvpn anymore,
> I configure my vpn container using a dedicated lan IP with the macvlan driver.
> with a twist of iptable and ipv4 forwaring I can use this dedicated ip as router on my Lan (but I've to disable ipv6 at the moment).
> 
> I'm also able to access the service on each container though this dedicated lan ip.
> 
> As for accessing them remotely, I only access HTTP(s) services through a traefik reverse proxy on my non vpn external IP. I could do it on my vpn, but not Nordvpn user, as it doesn't support port forwarding.

Could you please provide a detailed setup gide how you manage to get it to work with a macvlan ip and the ipv4 forwarding? I’m interested in setting up that way 
Thanks for sharing
