### ISSUE TITLE
neither stdin nor stderr are a tty device and you have neither a controlling tty nor systemd

### ISSUE THREAD

**Issue by ComatoseHub** [azinchen/nordvpn#99]
[_vpn_logs.txt](https://github.com/azinchen/nordvpn/files/7919657/_vpn_logs.txt)
I have attached my log file but cannot figure out why this container will not function. Below is my compose entry.

vpn:
    image: azinchen/nordvpn:latest
    container_name: vpn
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    ports:
      - 8080:8080 
      - 9696:9696 
      - 8989:8989 
      - 7878:7878 
    environment:
      - USER=******
      - PASSWORD=******
      - COUNTRY=38;227;228
      - GROUP=15
      - RANDOM_TOP=10
      - RECREATE_VPN_CRON=15 */5 * * *
      - NETWORK=192.168.1.0/24
    restart: unless-stopped

**Comment by azinchen** [comment]
Hi,

What is your host system?

**Comment by ComatoseHub** [comment]
Ubuntu server 20.04, is the os. Not sure if that is what you mean.

**Comment by ComatoseHub** [comment]
Any update on this?

**Comment by ComatoseHub** [comment]
Closing as I have found another solution.
